<?php
/**
 *   ╲          ╱
 * ╭──────────────╮  COPYRIGHT (C) 2016 GINGER PAYMENTS B.V.
 * │╭──╮      ╭──╮│
 * ││//│      │//││  This software is released under the terms of the
 * │╰──╯      ╰──╯│  GNU General Public License version 3 or later.
 * ╰──────────────╯
 *   ╭──────────╮    https://www.gnu.org/licenses/gpl-3.0.txt
 *   │ () () () │
 *
 * @category    Ginger
 * @package     Ginger_Ginger
 * @author      Ginger Payments B.V. (info@gingerpayments.com)
 * @version     v0.0.4
 * @copyright   Copyright (c) 2016 Ginger Payments B.V. (https://www.gingerpayments.com)
 * @license     https://www.gnu.org/licenses/gpl-3.0.txt
 *
 **/
?>
<?php /** @var $this Mage_Checkout_Block_Onepage_Success */ ?>
<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>

<?php if ($reference = Mage::app()->getRequest()->getParam('reference')): ?>
    <?php
    /** @var $order Mage_Sales_Model_Order */
    $order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId());

    /** @var $_helper Ginger_Ginger_Helper_Banktransfer */
    $_helper = Mage::helper('ginger/banktransfer');
    ?>
    <b><?php echo $this->__('Payment instructions:') ?></b><br/>
    <?php echo $this->__('Please use the following data to make the banktransfer') ?><br/>
    <?php echo nl2br($_helper->getSuccessHtml($order, $reference)) ?>
    <br/>
    <?php echo $this->__('Ginger Payments processes the payments for'); ?><?php echo Mage::app()->getGroup()->getName() ?>
    <br/>
    <br/>
    <?php echo $this->__('(!) Don\'t forget to use the reference in your payment. Without the reference the processing of your payment can take more time!'); ?>
    </p>
<?php endif ?>

<?php if ($this->getOrderId()): ?>
    <?php if ($this->getCanViewOrder()) : ?>
        <p><?php echo $this->__('Your order # is: %s.',
                sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getViewOrderUrl()),
                    $this->escapeHtml($this->getOrderId()))) ?></p>
    <?php else : ?>
        <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
    <?php endif; ?>
    <p><?php echo $this->__('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
    <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) : ?>
        <p>
            <?php echo $this->__('Click <a href="%s" onclick="this.target=\'_blank\'">here to print</a> a copy of your order confirmation.',
                $this->getPrintUrl()) ?>
            <?php echo $this->getChildHtml() ?>
        </p>
    <?php endif; ?>
<?php endif; ?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.',
            sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()),
                $this->escapeHtml($this->getAgreementRefId()))) ?></p>
<?php endif; ?>

<?php if ($profiles = $this->getRecurringProfiles()): ?>
    <p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
    <ul class="disc">
        <?php foreach ($profiles as $profile): ?>
            <?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>',
                $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile,
                    'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id'))); ?>
            <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml,
                    $this->escapeHtml($this->getObjectData($profile, 'schedule_description'))) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>

<div class="buttons-set">
    <button type="button" class="button" title="<?php echo $this->__('Continue Shopping') ?>"
            onclick="window.location='<?php echo $this->getUrl() ?>'">
        <span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
</div>